import type { Metadata } from 'next';
import LegalLayout from '@/components/LegalLayout';

export const metadata: Metadata = {
  title: 'Terms & Conditions | Wishelier',
  description: 'Terms and Conditions governing the use of Wishelier AI Birthday Website Builder.',
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms & Conditions" subtitle="Effective Date: July 31, 2026">

      <p>
        Welcome to Wishelier. These Terms and Conditions govern your use of the Wishelier AI Birthday Website Builder, operated by <strong style={{ color: 'var(--text-main)' }}>Ayush Kumar Singh</strong> (Sole Proprietor). By accessing or using our service, you agree to comply with these terms.
      </p>

      <h2 style={{ color: 'var(--text-main)', fontSize: '1.125rem', fontWeight: 800 }}>1. AI Services & Content Generation</h2>
      <p>Wishelier uses multi-agent Artificial Intelligence to programmatically generate websites.</p>
      <ul className="space-y-2" style={{ paddingLeft: '1.25rem' }}>
        <li><strong style={{ color: 'var(--text-main)' }}>User Responsibility:</strong> You are solely responsible for the &quot;Input&quot; (text, relationship details, and images) you provide. You must ensure your Input does not violate Indian law, infringe on third-party intellectual property, or breach privacy rights.</li>
        <li><strong style={{ color: 'var(--text-main)' }}>Accuracy:</strong> You are responsible for reviewing the generated &quot;Output&quot; (the preview website) for appropriateness and accuracy before finalizing your purchase and sharing the link.</li>
      </ul>

      <h2 style={{ color: 'var(--text-main)', fontSize: '1.125rem', fontWeight: 800 }}>2. Statutory Duties of Users</h2>
      <p>Under the Digital Personal Data Protection Act, 2023, you have a statutory duty to provide verifiable and authentic information. Users must not:</p>
      <ul className="space-y-2" style={{ paddingLeft: '1.25rem' }}>
        <li>Impersonate another person while providing personal data.</li>
        <li>Register a false or frivolous grievance.</li>
        <li>Suppress material information.</li>
      </ul>
      <p>Violation of these duties may attract legal consequences.</p>

      <h2 style={{ color: 'var(--text-main)', fontSize: '1.125rem', fontWeight: 800 }}>3. AI Disclosure (SGI Compliance)</h2>
      <p>
        In compliance with Indian Information Technology regulations regarding Synthetically Generated Information (SGI), we transparently disclose that the final website layout, code, and text copy are generated using Artificial Intelligence based on your inputs.
      </p>

      <h2 style={{ color: 'var(--text-main)', fontSize: '1.125rem', fontWeight: 800 }}>4. Limitation of Liability</h2>
      <p>
        The websites generated by Wishelier reflect the inputs provided by the user and interpreted by our AI. They do not represent the views of Wishelier or Ayush Kumar Singh. To the maximum extent permitted by Indian law, our liability is strictly limited to the amount paid for the service (₹29). We are not liable for any indirect, emotional, or consequential damages resulting from the use of our service or the generated websites.
      </p>

      <h2 style={{ color: 'var(--text-main)', fontSize: '1.125rem', fontWeight: 800 }}>5. Governing Law and Jurisdiction</h2>
      <p>
        These Terms shall be governed by and interpreted in accordance with the laws of India. Any disputes arising out of these Terms shall be subject to the exclusive jurisdiction of the courts located in Ghaziabad, Uttar Pradesh.
      </p>

    </LegalLayout>
  );
}
